default: &default
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000
  host: localhost
  
development:
  <<: *default

test:
  <<: *default
  
production:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: <%= ENV['database'] %>
  username: <%= ENV['db_username'] %>
  password: <%= ENV['db_password'] %>
  port: 5432
  host: <%= ENV['db_host'] %>

