default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV['database'] %>
  username: <%= ENV['db_username'] %>
  password: <%= ENV['db_password'] %>
  host: localhost
  
test:
  <<: *default
  database: <%= ENV['database'] %>
  username: <%= ENV['db_username'] %>
  password: <%= ENV['db_password'] %>
  host: localhost
production:
  <<: *default
  adapter: postgresql
  database: <%= ENV['database'] %>
  username: <%= ENV['db_username'] %>
  password: <%= ENV['db_password'] %>
  port: 5432
  host: <%= ENV['db_host'] %>
  

